### ISSUE TITLE
The hero video might be making the website wider than the screen

### ISSUE THREAD

**Issue by cynthetic-boop** [BeyondMelee/BeyondMelee.github.io#6]
I got a horizontal scroll on the home page, im pretty sure it has something to do with the new hero video, i saw something had -8px on left and right so that might be part of it? idk tho

**Comment by ggliv** [comment]
probably the `+ 16px` on this?
https://github.com/BeyondMelee/BeyondMelee.github.io/blob/9196b614674f8b7d4d9c76284450e63bdd1020a0/css/style.css#L881

**Comment by cynthetic-boop** [comment]
> 
> 
> probably the `+ 16px` on this?
> 
> https://github.com/BeyondMelee/BeyondMelee.github.io/blob/9196b614674f8b7d4d9c76284450e63bdd1020a0/css/style.css#L881

it looks like that could be doing it, but when i removed the -8px from left and right that was generated it didnt go away.  idk if thats due to it being not reloaded or what, but i couldnt figure it out

**Comment by ggliv** [comment]
its definitely that, I looked over it with dev tools
linked pr will fix the issue

**Comment by cynthetic-boop** [comment]
closed with a more simple solution than pr#12 #
